version: "3.7"
services:
  proyectos-backend :
    container_name: proyectos-backend
    image: proyectos-backend:v1
    build:
      context: .
    ports:
      - "4001"
    environment:
     - MONGO_URI=${MONGO_URI}
     - PORT=  4001
    networks:
      - proyectos-app
  balanceador-carga:
    container_name: balanceador-carga
    image: balanceador-carga:v1
    build:
      context: ./balanceador
    ports:
      - "4004:80"
    networks:
      - proyectos-app
networks:
  proyectos-app:
